sonar.projectKey=blog-pessoal-dotnet
sonar.working.directory=C:\\Dev\\BlogPessoalBackend\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Dev\\BlogPessoalBackend
sonar.pullrequest.cache.basepath=C:\\Dev\\BlogPessoalBackend
sonar.sources=\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\appsettings.Development.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\appsettings.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\obj\\BlogPessoal.csproj.nuget.dgspec.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\obj\\project.assets.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\Properties\\launchSettings.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.deps.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.runtimeconfig.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.staticwebassets.endpoints.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\bin\\Debug\\net10.0\\BuildHost-net472\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe.config",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.deps.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal\\bin\\Debug\\net10.0\\BuildHost-netcore\\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.runtimeconfig.json"

33D49902-92BF-0893-2662-B954E9340E71.sonar.projectKey=blog-pessoal-dotnet:33D49902-92BF-0893-2662-B954E9340E71
33D49902-92BF-0893-2662-B954E9340E71.sonar.projectName=BlogPessoal.Tests
33D49902-92BF-0893-2662-B954E9340E71.sonar.projectBaseDir=C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests
33D49902-92BF-0893-2662-B954E9340E71.sonar.sourceEncoding=utf-8
33D49902-92BF-0893-2662-B954E9340E71.sonar.sources=
33D49902-92BF-0893-2662-B954E9340E71.sonar.tests=\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\GeminiServiceTests.cs",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\TemaServiceTests.cs",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\UsuarioServiceTests.cs",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\obj\\BlogPessoal.Tests.csproj.nuget.dgspec.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\obj\\project.assets.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\bin\\Debug\\net10.0\\appsettings.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\bin\\Debug\\net10.0\\BlogPessoal.deps.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\bin\\Debug\\net10.0\\BlogPessoal.runtimeconfig.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\bin\\Debug\\net10.0\\BlogPessoal.staticwebassets.endpoints.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\bin\\Debug\\net10.0\\BlogPessoal.Tests.deps.json",\
"C:\\Dev\\BlogPessoalBackend\\BlogPessoal.Tests\\bin\\Debug\\net10.0\\BlogPessoal.Tests.runtimeconfig.json"

33D49902-92BF-0893-2662-B954E9340E71.sonar.cs.analyzer.projectOutPaths=\
"C:\\Dev\\BlogPessoalBackend\\.sonarqube\\out\\1"
33D49902-92BF-0893-2662-B954E9340E71.sonar.cs.roslyn.reportFilePaths=\
"C:\\Dev\\BlogPessoalBackend\\.sonarqube\\out\\1\\Issues.json"
33D49902-92BF-0893-2662-B954E9340E71.sonar.cs.scanner.telemetry=\
"C:\\Dev\\BlogPessoalBackend\\.sonarqube\\out\\1\\Telemetry.json"

33D49902-92BF-0893-2662-B954E9340E71.sonar.working.directory=C:\\Dev\\BlogPessoalBackend\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=33D49902-92BF-0893-2662-B954E9340E71

